api_server:
  http:
    cors:
      enabled: true
      access_control_allow_origins: ["http://localhost:3000"]  # Substitua pelo dom√≠nio do seu aplicativo React
      access_control_allow_methods: ["GET", "OPTIONS", "POST", "HEAD", "PUT"]
      access_control_allow_credentials: true
      access_control_allow_headers: ["*"]
      access_control_allow_origin_regex: 'https://.*\.my_org\.com'
      access_control_max_age: 1200
      access_control_expose_headers: ["Content-Length"]
